### ISSUE TITLE
latest available Pod 2.0.0 is not compatible with Swift 3

### ISSUE THREAD

**Issue by mvonballmo** [jgretz/CoreMeta#21]
Version 2.0.1 at master HEAD works as a direct dependency in my Podfile, but I can't specify the git repository as the version for s.dependency in the podspec.

Can you please release the latest version as 2.0.1 so that I can use the Podfile without using the git repo?

**Comment by jgretz** [comment]
Just updated to version 2.0.1 on cocoapods

**Comment by mvonballmo** [comment]
Thank you!
