### ISSUE TITLE
Multiple containers question

### ISSUE THREAD

**Issue by aceontech** [jgretz/CoreMeta#8]
Hi,

I'm looking into the IOC part of CoreMeta and was wondering whether your library can support multiple containers and the ability to clear the container at will (provided all references to objects in the registry are weak)?

Thanks!

**Comment by jgretz** [comment]
Yes is the answer to both questions 

Slightly longer answer:
1) You can instantiate and control as many instances of containers as you wish. 

I do provide syntactic sugar off the shared container singleton in the NSObject+IOC category - but its not required to be used. The container is self-contained. 

2) There are 4 clear methods - all, and more surgical ones by key, class, and protocol

Happy to answer any other questions - hope its helpful
